### PR TITLE
perf(intersect): Improve Intersect Solids Component 

### PR DESCRIPTION
**Pull request by chriswmackey**
This commit refactors the component for intersecting solid breps with one another to create matching surfaces for energy models. It uses [this new code here over in ladybug_rhino](https://github.com/ladybug-tools/ladybug-rhino/blob/master/ladybug_rhino/intersect.py#L19-L180), which uses a bounding box check that greatly reduces the run time from the honeybee legacy version.  The single-core calculation runs in under half the time of honeybee-legacy and the parallel version runs in 1/10th of the time on my 12-core machine.

### CODE REVIEW

**Comment by chriswmackey** [comment]
BTW, here is a screenshot showing the improved performance over the legacy version and @MingboPeng 's version of the component in Ironbug:
image

**Comment by MingboPeng** [comment]
Hi @chriswmackey, this is supper cool. So happy that you have this done in new version. 
One question, do we really need an input "parallel_"? Under what situation that won't use the parallel compute?

**Comment by chriswmackey** [comment]
Thanks @MingboPeng .  I think we always want to give people the option of running things on single core vs. parallel just because running two grasshopper files in parallel at the same time will result in them both performing pretty poorly (and possibly overloading the system to the point that the Windows UI is unresponsive, as I've experienced a few times).

Also, I am not sure how `System.Threading.Tasks` works in Rhino for Mac and I know that we definitely want to ensure that Honeybee[+] is run-able on Mac (especially for this new generation of Architecture students, many of whom are doing all of their studio work in Mac OS).  I'll try to do a test of the parallel functionality on a Mac in the next couple of weeks to see if this is an issue.  If it's not a problem, we can make parallelization the default option.

**Comment by chriswmackey** [comment]
@mingbopeng ,

I did some testing in Rhino for Mac and there were no issues with using System.Tasks.Parallel. The calculation ran well in parallel and the only difference was that the Mac asked for permission the first time I ran the component. So we can make running in parallel the default options and I will send a PR shortly.

**Pull request merged**
