### PR TITLE
fix(Components with wireframe outputs): Fix to output hole curves

### PR DESCRIPTION
**Pull request by devngc**
Fix to output hole curves with boundary curves

### CODE REVIEW

**Review by chriswmackey — APPROVED** [review]
All looks good. Thanks @devngc !

**Review by chriswmackey — CHANGES_REQUESTED** [review]
Actually, we also need the following components to be updated:

* "HB Color Room Attributes
* HB Label Rooms
* HB Visualize Wireframe

**Comment by devngc** [comment]
I changed the HB Vizualize Wireframe component. The rest are not affected as they are using `from_polyface_to_wireframe` method that we did not change.

**Review by chriswmackey — APPROVED** [review]
Ah, good point, @devngc . We're all good, then. Let's merge.

**Pull request merged**
